#!/bin/sh

#. /lib/live/config.sh

## live-config(7) - System Configuration Components
## Copyright (C) 2016-2020 The Debian Live team
## Copyright (C) 2006-2015 Daniel Baumann <mail@daniel-baumann.ch>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


#set -e


Config (){
    if test -f /home/.login/passwd; then
	TMP=$(mktemp -d)
	/usr/share/ltsp/client/login/pwmerge /home/.login/ /etc/ $TMP/
	cp -a $TMP/* /etc/
	rm -r $TMP

	#prevent running these ...
	touch /var/lib/live/config/live-debconfig_passwd
        touch /var/lib/live/config/user-setup
	touch /var/lib/live/config/sudo
    fi
}

Config
